name: Notificar en Slack cuando se cierra un Issue

on:
  issues:
    types:
      - closed  # Este evento se dispara cuando un issue se cierra

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 *Issue Cerrado* en *${{ github.repository }}*",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "Issue #${{ github.event.issue.number }} - ${{ github.event.issue.title }}",
                  "title_link": "${{ github.event.issue.html_url }}",
                  "fields": [
                    {
                      "title": "Estado",
                      "value": "Cerrado ✅",
                      "short": true
                    },
                    {
                      "title": "Responsable",
                      "value": "${{ github.actor }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
